#!/bin/sh /etc/rc.common

START=99

USE_PROCD=1
PROG=/usr/share/urender/onlinecheck.uc

start_service() {
	local interval=$(uci -q get onlinecheck.@config[0].check_interval)
	[ -z "$interval" ] && return
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn 1 $interval 0
	procd_close_instance
}
